/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RPNCalculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        RPNCalculator cut = new RPNCalculator();
        cut.process("333 0 /");
        System.out.println("Stack: " + cut.printStack());
    }
}
