/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RPNCalculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        RPNCalculator cut = new RPNCalculator();
        cut.process("1 +");
        System.out.println("Stack: " + cut.printStack());
        cut.process("1 2 3 4 5 clear undo 4 5 6 undo undo 7 8 9");
        System.out.println("Stack: " + cut.printStack());
    }
}
